# Generated by Django 4.1.3 on 2022-11-17 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('confirmation_link', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('bio', models.CharField(max_length=255, null=True)),
                ('avatar_path', models.ImageField(null=True, upload_to='avatars')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('posts', models.ManyToManyField(related_name='tags', to='djangogramm.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangogramm.user'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangogramm.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangogramm.user')),
            ],
            options={
                'db_table': 'like_',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='images')),
                ('position', models.IntegerField(default=1)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangogramm.post')),
            ],
        ),
    ]
