# Generated by Django 4.1.3 on 2022-11-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='djangogramm_like_',
        ),
    ]
