# Generated by Django 4.1.3 on 2022-11-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0002_alter_like_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='djangogramm_like',
        ),
    ]
